-- CreateEnum
CREATE TYPE "HabitScoringType" AS ENUM ('LINEAR_POSITIVE_CAPPED', 'LINEAR_NEGATIVE_CAPPED', 'THRESHOLD_TARGET', 'ONE_OFF_BONUS');

-- AlterTable
ALTER TABLE "Habit" ADD COLUMN     "scoringType" "HabitScoringType" NOT NULL DEFAULT 'LINEAR_POSITIVE_CAPPED';
